GlobalNamesArchitecture/gnparser

- src/main/scala/org/globalnames/formatters/Details.scala
Another round of cleanups. Sorry.. Now I am satisfied.
> = Minor cleanup to Details

- README.md
Fixes #33, not very useful badge as badge IMO, but makes a link to the waffle dashboard
> Issues badge

- src/main/scala/org/globalnames/formatters/Details.scala
- src/main/scala/org/globalnames/parser/ParserClean.scala
- src/main/scala/org/globalnames/parser/ScientificNameParser.scala
- src/main/scala/org/globalnames/parser/Util.scala
Fix #31 TaskList: fix hack with 'ж' and 'щ'
> 31 fix hacks

- src/main/scala/org/globalnames/parser/Util.scala
- src/test/resources/test_data.txt
> = Capitalize upper case authors with dash

- src/main/scala/org/globalnames/parser/ScientificNameParser.scala
Missed them when copmleted hack fix
> = Remove unused functions

- src/main/scala/org/globalnames/parser/TrackingPositionsUnescapeHtml4Translator.scala
For more information take a look at [scala-user group](https://groups.google.com/forum/#!topic/scala-user/h_ldeu_Retk)
> = Fix cast to Array[Array[CharSequence]]

- parser/src/main/scala/org/globalnames/formatters/Canonizer.scala
- parser/src/main/scala/org/globalnames/formatters/Details.scala
- parser/src/main/scala/org/globalnames/formatters/Normalizer.scala
- parser/src/main/scala/org/globalnames/formatters/Positions.scala
- parser/src/main/scala/org/globalnames/parser/AST.scala
- parser/src/main/scala/org/globalnames/parser/Parser.scala
- parser/src/main/scala/org/globalnames/parser/ParserClean.scala
- parser/src/main/scala/org/globalnames/parser/ScientificNameParser.scala
closes #85 
I tried several approaches. Alas, most of them overcomplicates code. I left the simplest one: couple Input and Ast nodes through Parser result.
> 85 refactor ast nodes

- parser/src/main/scala/org/globalnames/formatters/Canonizer.scala
- parser/src/main/scala/org/globalnames/formatters/Normalizer.scala
- parser/src/main/scala/org/globalnames/parser/AST.scala
- parser/src/main/scala/org/globalnames/parser/Parser.scala
- parser/src/main/scala/org/globalnames/parser/ParserWarnings.scala
- parser/src/main/scala/org/globalnames/parser/ScientificNameParser.scala
> = Add parsing warnings

- build.sbt
- examples/src/main/java/Parser.java
- parser/src/main/scala/org/globalnames/parser/GnParser.scala
- parser/src/main/scala/org/globalnames/parser/ParServer.scala
- parser/src/main/scala/org/globalnames/parser/ScientificNameParser.scala
> = Add example in Java

- parser/src/main/scala/org/globalnames/parser/ParserWarnings.scala
> = Fix "Adapting argument list by creating a 2-tuple"

- parser/src/test/scala/org/globalnames/parser/ScientificNameParserSpec.scala
I noticed that we have been using this debug version for quite a long. We missed changes is a large commit in past.
> = Revert ScientificNameParserSpec

- README.md
- examples/R/parser.R
> = Add example in R language

- README.md
- examples/jruby/parser.rb
> = JRuby example

- README.md
needs to be rebased with only last commit after merge of #128
> Standardise readme links

- README.md
- build.sbt
- parser/src/main/scala/org/globalnames/parser/ScientificNameParser.scala
> = Get rid of hacks in UUIDv5 generation

- parser/src/main/scala/org/globalnames/parser/GnParser.scala
Oups we use deprecated species name in our CLI example and outdated script name
> = change example to existing species

- JSON_FIELDS.md
> = JSON fields documentation

- README.md
- build.sbt
- runner/src/main/scala/org/globalnames/GnParser.scala
- runner/src/main/scala/org/globalnames/ParServer.scala
> = Make parser runner project separate from parser library

- README.md
- build.sbt
- project/sbt-native-packager.sbt
- runner/src/main/scala/org/globalnames/GnParser.scala
- runner/src/templates/bash-template
> = Clean up CLI and help messages

- .travis.yml
- README.md
- build.sbt
- project/web-plugins.sbt
- web/app/controllers/Application.scala
- web/app/controllers/util/Messages.scala
- web/app/views/index.scala.html
- web/conf/application.conf
- web/conf/routes
- web/test/ApplicationSpec.scala
> = Add Web GUI to project

- .travis.yml
> = add 2.11.0 to travis

- README.md
> = :memo: README for the first release

- web/app/controllers/Application.scala
> = fix #167 remove artificial trailing space warning

- parser/src/main/scala/org/globalnames/parser/ScientificNameParser.scala
- runner/src/main/scala/org/globalnames/GnParser.scala
> = Use stderr for errors

- README.md
- build.sbt
- examples/java-scala/src/main/java/org/globalnames/parser/examples/ParserJava.java
- examples/java-scala/src/main/scala/org/globalnames/parser/examples/ParserScala.scala
fix #162 
Should be rebased after #176 is merged
> 162 scala example

- .gitignore
- build.sbt
- project/web-plugins.sbt
- web/app/views/index.scala.html
> = Fix serving static resources

- build.sbt
- project/sbt-pgp.sbt
> = Configure v0.1.0 publishing

- .travis.yml
- README.md
- build.sbt
> = Run on Scala 2.10

- README.md
> = Fix #192 update README for release

- CHANGELOG.md
> = Fix #170 add changelog file

- TCS.md
> = Fix #202: modify terms for JSON fields

- README.md
- benchmark/src/main/scala/org/globalnames/ScientificNameParserBenchmark.scala
- build.sbt
- project/sbt-jmh.sbt
> = Add benchmark subproject

- runner/src/main/scala/org/globalnames/GnParser.scala
fix #35 
Result of running for 16 core machine:
```
gnparser$ time ./runner/target/universal/stage/bin/gnparse -input 100k.txt -Dparallelism=2 2>/dev/null
running with parallelism: 2
real    0m23.031s
user    1m24.557s
sys     0m3.164s
gnparser$ time ./runner/target/universal/stage/bin/gnparse -input 100k.txt -Dparallelism=4 2>/dev/null
running with parallelism: 4
real    0m15.566s
user    1m28.006s
sys     0m3.740s
gnparser$ time ./runner/target/universal/stage/bin/gnparse -input 100k.txt -Dparallelism=8 2>/dev/null
running with parallelism: 8
real    0m13.346s
user    2m4.244s
sys     0m4.052s
gnparser$ time ./runner/target/universal/stage/bin/gnparse -input 100k.txt -Dparallelism=16 2>/dev/null
running with parallelism: 16
real    0m13.239s
user    2m25.073s
sys     0m4.552s
gnparser$ …
```
> = Add parallel parsing of input file

- CHANGELOG.md
- README.rst
> 209 update docs

- parser/src/test/resources/test_data.txt
An old issue which had been fixed by itself. Added tests for it
> = Fix #89 dash in the end start

- parser/src/main/scala/org/globalnames/parser/Util.scala
> = Cleanup Util object

- parser/src/main/scala/org/globalnames/formatters/JsonRenderer.scala
- parser/src/main/scala/org/globalnames/parser/ScientificNameParser.scala
> + Make ScientificNameParser.id of UUID type

- README.rst
- build.sbt
- parser/src/main/scala/org/globalnames/parser/AST.scala
- parser/src/main/scala/org/globalnames/parser/Parser.scala
- parser/src/main/scala/org/globalnames/parser/ScientificNameParser.scala
- parser/src/main/scala/org/globalnames/parser/Warning.scala
- project/build.properties
- project/web-plugins.sbt
> = Update dependencies

- build.sbt
- project/sbt-buildinfo.sbt
- runner/src/main/scala/org/globalnames/GnParser.scala
- runner/src/main/scala/org/globalnames/ParServer.scala
> Runner args for simple delimited-string output 

- parser/src/test/resources/test_data.txt
small cleanup of trailing spaces and folding marks
> = cleanup tests data

- README.rst
- build.sbt
- examples/spark/README.rst
- examples/spark/src/main/scala/org/globalnames/parser/examples/ParserSpark.scala
- spark-python/src/main/scala/org/globalnames/parser/spark/Parser.scala
> + Add Apache Spark example

- README.rst
- build.sbt
- runner/src/main/scala/org/globalnames/GnParser.scala
- runner/src/main/scala/org/globalnames/parser/runner/tcp/TcpServer.scala
- runner/src/main/scala/org/globalnames/parser/runner/web/controllers/WebServer.scala
> 250 docker

- CHANGELOG.md
- README.rst
- RELEASE-STEPS.md
- build.sbt
- runner/src/templates/bash-template
> 234 release

- parser/src/main/scala/org/globalnames/parser/Parser.scala
- parser/src/test/resources/test_data.txt
> = Handle punctuation in the end of a name

- parser/src/main/scala/org/globalnames/parser/Parser.scala
- parser/src/test/resources/test_data.txt
> #329: Add `v.` for `von`

- parser/src/main/scala/org/globalnames/parser/Parser.scala
- parser/src/main/scala/org/globalnames/parser/Util.scala
- parser/src/test/resources/test_data.txt
fix #321 
@dimus , please place `Östrupia Heiden ex Hustedt, 1935` name to appropriate section.
> #321: Support `Oe` unicode character

- parser/src/main/scala/org/globalnames/parser/Parser.scala
- parser/src/test/resources/test_data.txt
> #305: support `el` in author name

- parser/src/main/scala/org/globalnames/parser/Parser.scala
- parser/src/test/resources/test_data.txt
> #320: Support hyphenated genus name with capitalised part

- parser/src/main/scala/org/globalnames/parser/Parser.scala
- parser/src/test/resources/test_data.txt
> fix #328: handle lowercase subgenus (that might be superspecies)

- parser/src/main/scala/org/globalnames/parser/ScientificNameParser.scala
- parser/src/test/resources/test_data.txt
> 327 handle cf

- parser/src/main/scala/org/globalnames/UuidGenerator.scala
- parser/src/main/scala/org/globalnames/parser/AST.scala
- parser/src/main/scala/org/globalnames/parser/Parser.scala
- parser/src/main/scala/org/globalnames/parser/Preprocessor.scala
- parser/src/main/scala/org/globalnames/parser/ScientificNameParser.scala
- parser/src/main/scala/org/globalnames/parser/Warning.scala
- parser/src/main/scala/org/globalnames/parser/formatters/Canonizer.scala
- parser/src/main/scala/org/globalnames/parser/formatters/DelimitedStringRenderer.scala
- parser/src/main/scala/org/globalnames/parser/formatters/JsonRenderer.scala
- parser/src/test/resources/test_data.txt
- parser/src/test/scala/org/globalnames/UuidGeneratorSpec.scala
- parser/src/test/scala/org/globalnames/parser/ScientificNameParserSpec.scala
fix: https://github.com/GlobalNamesArchitecture/gnparser/issues/327
> fix cf handling

- parser/src/main/scala/org/globalnames/parser/Parser.scala
- parser/src/test/resources/test_data.txt
> fix #332: Add uninomial with approximation

- README.rst
- build.sbt
- runner/src/main/scala/org/globalnames/GnParser.scala
- runner/src/main/scala/org/globalnames/parser/runner/GnParser.scala
- runner/src/main/scala/org/globalnames/parser/runner/tcp/TcpServer.scala
- runner/src/main/scala/org/globalnames/parser/runner/web/controllers/WebServer.scala
- runner/src/test/scala/org/globalnames/parser/runner/GnParserSpec.scala
> 346 stdin redirect

- README.rst
These changes include fixes in grammar from Paddy to README file
> gnpaper_edits

- parser/src/main/scala/org/globalnames/parser/Parser.scala
- parser/src/test/resources/test_data.txt
> #249: parse “von dem” author prefix correctly

- parser/src/test/resources/test_data.txt
fix #252 #255 
test_data.txt should be fixed
> 252 tick t parse

- parser/src/main/scala/org/globalnames/parser/Preprocessor.scala
- parser/src/test/resources/test_data.txt
> #246: distinguish cases when ‘satellite’ is not a virus

- parser/src/main/scala/org/globalnames/parser/Parser.scala
- parser/src/main/scala/org/globalnames/parser/Util.scala
- parser/src/test/resources/test_data.txt
fix #386 
@dimus please check if `test_data` is OK for you. If it is then put it in an appropriate section.
> 386 nums in species

- parser/src/main/scala/org/globalnames/parser/Preprocessor.scala
- parser/src/test/resources/test_data.txt
> Fix #382: support emend in the name

- parser/src/main/scala/org/globalnames/parser/Preprocessor.scala
- parser/src/test/resources/test_data.txt
> Fix #379: Do not parse “Not” in uninomial/genus

- parser/src/main/scala/org/globalnames/parser/Parser.scala
- parser/src/main/scala/org/globalnames/parser/Preprocessor.scala
- parser/src/test/resources/test_data.txt
> Fix #401: add more ranks and two-letter abbreviations
